# Generated by Django 5.0.7 on 2024-10-26 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Назва замовлення')),
                ('description', models.TextField(max_length=5000, verbose_name='Опис')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('order_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='sales_management.order')),
            ],
        ),
        migrations.CreateModel(
            name='TakenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Перегяд'), (2, 'Надіслана калькуляція'), (3, 'В процесі'), (4, 'Готово'), (5, 'Відхилено'), (6, 'Скасовано користувачем')], default=1)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sales_management.order')),
            ],
        ),
    ]
