# Generated by Django 5.0.7 on 2024-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0002_order_created_at_takenorder_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenorder',
            name='response',
            field=models.CharField(default='Немає відповіді', max_length=200, verbose_name='manager_response'),
        ),
    ]
