# Generated by Django 5.0.7 on 2024-10-26 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0003_takenorder_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenorder',
            name='manager',
        ),
        migrations.AlterField(
            model_name='takenorder',
            name='response',
            field=models.TextField(default='Немає відповіді', max_length=200, verbose_name='Відповідь:'),
        ),
        migrations.AlterField(
            model_name='takenorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Перегяд'), (2, 'Надіслана калькуляція'), (3, 'В процесі'), (4, 'Готово'), (5, 'Відхилено'), (6, 'Скасовано користувачем')], default=1, verbose_name='Статус:'),
        ),
        migrations.AddField(
            model_name='takenorder',
            name='manager',
            field=models.ManyToManyField(related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
