# Generated by Django 5.0.7 on 2024-10-26 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0004_remove_takenorder_manager_alter_takenorder_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenorder',
            name='manager',
        ),
        migrations.AddField(
            model_name='takenorder',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
